name: Terraform CI (Dev)

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  terraform:
    name: Terraform Lint & Validate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Format Terraform
        run: terraform fmt -check -recursive

      - name: Init Terraform
        run: terraform init

      - name: Validate Terraform
        run: terraform validate
